# ---------------------------------------------------------------
# Site Information Settings
# ---------------------------------------------------------------

# Header Menu
menu:
  Home: /
  Archives: archives
  Categories: categories
  Tags: tags
  About: about
rss: /atom.xml

since: 2013

# Set default keywords (Use a comma to separate)
keywords: "Kim,index,computer,node.js,php,laravel,github,aboutme"

# Put your favicon.ico into `hexo-site/themes/hiero/source/` directory.
favicon: css/images/favicon.ico


# Put your avatar.jpg into `hexo-site/themes/hiero/source/` directory.
# url is target link (E.g. `url: https://hexo.io/logo.svg` or `url: css/images/mylogo.jpg`)
avatar: 
  enable: false
  width: 124
  height: 124
  bottom: 10
  url: https://hexo.io/logo.svg
  

# AboutPage background
# about_big_image: [css/images/pose.jpg, https://source.unsplash.com/collection/954550/1920x1080]
about_big_image: [
  https://unsplash.it/640/480?random
]


# Homepage thumbnail
random_thumb: false


# Content
fancybox: true


# Sidebar
sidebar: right
widgets:
- search
- social
- recent_posts
- category
- tag
- tagcloud
- archive

# Social Links
# Key is the name of FontAwsome icon.
# Value is the target link (E.g. GitHub: https://github.com/iTimeTraveler)
social:
  Github: http://bit.ly/2fXTRW6
  Weibo: http://bit.ly/2suM5pJ
  Twitter: http://bit.ly/2ry6Jny
  Facebook: http://bit.ly/2sRr7Um
  Google-plus: http://bit.ly/2tmT3gr
  Instagram: http://bit.ly/2suvi63
  Pinterest: http://bit.ly/2sRgf9g
  Flickr: http://bit.ly/2rL3ddF
  email: white.shopping@gmail.com


# Search
search:
    insight: true # you need to install `hexo-generator-json-content` before using Insight Search
    swiftype: # enter swiftype install key here
    baidu: false # you need to disable other search engines to use Baidu search, options: true, false


# comment ShortName, you can choose only ONE to display.
gentie_productKey: #your-gentie-product-key
duoshuo_shortname:
disqus_shortname: pgub
livere_shortname: 
uyan_uid: 
wumii: 

# Code Highlight theme
# Available value:
#    default | normal | night | night eighties | night blue | night bright
# https://github.com/chriskempson/tomorrow-theme
highlight_theme: night



# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive


# widget behavior
archive_type: 'monthly'
show_count: true

# Google Webmaster tools verification setting
# See: https://www.google.com/webmasters/
google_site_verification: U667b_JSMnFClMdKcd5viPuxY-ujdLE9wJPBUnoxBuk
baidu_site_verification: CebeUMJ0Zm
qihu_site_verification: 06e221ffb5c7a29b0d15adaf61347b34

# Miscellaneous
google_analytics: UA-46999556-16
gauges_analytics:
baidu_analytics: 037acb7dd5a8580c0b5631e0c2d7fcbe
tencent_analytics: 62678751
busuanzi_analytics: true
twitter: whitewhiter
google_plus: https://plus.google.com/u/1/104033068621914458442
fb_admins: 
fb_app_id:

# Facebook SDK Support.
# https://github.com/iissnan/hexo-theme-next/pull/410
facebook_sdk:
  enable: false
  app_id:       #<app_id>
  fb_admin:     #<user_id>
  like_button:  #true
  webmaster:    #true

# CNZZ count
cnzz_siteid: 1262380837

# Shareaholic
shareaholic_code: a3988232fa3b8f7b00b435ce0ade0df8

# donation button
donate:
    enable: false
    message: '如果觉得我的文章对您有用，请随意打赏。您的支持将鼓励我继续创作!'
    wechatImage: https://raw.githubusercontent.com/iTimeTraveler/iTimeTraveler.github.io/site/source/about/donate/images/WeChanQR.png
    alipayImage: https://raw.githubusercontent.com/iTimeTraveler/iTimeTraveler.github.io/site/source/about/donate/images/AliPayQR.jpg
